#!/usr/bin/env perl

use v5.36;
use strictures 2;

use Test::More;

use_ok('AoC::Solution::Day8');

my $solution = AoC::Solution::Day8->new(
    input => join("\n", qw(
        ............
        ........0...
        .....0......
        .......0....
        ....0.......
        ......A.....
        ............
        ............
        ........A...
        .........A..
        ............
        ............
    )),
);

is ($solution->part_1, 14, 'part_1');
is ($solution->part_2, 34, 'part_2');

done_testing;
